### ISSUE TITLE
Can't use pavr2gui as sudo on Wayland

### ISSUE THREAD

**Issue by Garbulix** [pololu/pololu-usb-avr-programmer-v2#1]
Wayland session forbids using GUI applications as sudo:
https://wiki.archlinux.org/index.php/Running_GUI_applications_as_root

I know there is a workaround with xhost (https://www.reddit.com/r/Fedora/comments/5eb633/solution_running_graphical_app_with_sudo_in/) or just using Xorg session (I am using this workaround), but I think these solutions should be only temporary.
Is there a way to make pavr2gui fully "compatible" with Wayland?

I am using Fedora 29.

**Comment by DavidEGrayson** [comment]
You should not need to run it with sudo.  If you install it according to the instructions in the [user's guide](https://www.pololu.com/docs/0J67), it installs a udev rule to make Pololu USB devices accessible to normal users, and the rule could be manually installed without much trouble.  Why are you running it with sudo?

**Comment by Garbulix** [comment]
You are right, sorry. 
I needed to run this as sudo, because I wanted to run binary file without installing all the program files (I dont like sh installers, because there is no easy clickable gui uninstallers - or maybe thats not true?)

Issue can be closed :)
